<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Compile Remove="kostki2_testy\**" />
		<EmbeddedResource Remove="kostki2_testy\**" />
		<None Remove="kostki2_testy\**" />
	</ItemGroup>
</Project>
